16 edit lists title
Pertempto/Lists pull request #23
Opened 2023-05-01 15:11 UTC by tycebrown

Added functionality to edit a list's title.

Points/considerations/questions:

  - Is the constructor `makeEditButton()` useless, duplicate code? 
  - Anything else need restyling, renaming, restructuring?

2023-05-01 15:24 UTC, tycebrown commented
Somehow dependent on issue #15 and PR #22 (search in single list).

2023-06-08 09:42 UTC, Pertempto requested changes
Looking pretty good! I don't like how the editing actions buttons are spread across with `MainAxisAlignment.spaceBetween`. I think they would look better all on the left side. Use a `Wrap` with the `spacing` parameter set to something like 8, 12, or 16.

2023-06-08 09:42 UTC, Pertempto commented on lib/view/editing_actions_modal_bottom_sheet.dart
>    factory EditingActionButton.makeDeleteButton(
```suggestion
  factory EditingActionButton.deleteButton(
```

2023-06-08 09:42 UTC, Pertempto commented on lib/view/editing_actions_modal_bottom_sheet.dart
> +  factory EditingActionButton.makeEditButton(
```suggestion
  factory EditingActionButton.editButton(
```

2023-06-15 23:12 UTC, Pertempto commented
@tycebrown For future reference, please let the reviewer mark the threads as resolved. That way, they can double check that they were handled correctly.

2023-06-15 23:17 UTC, Pertempto approved these changes

2023-06-15 23:18 UTC, merged

2023-06-16 01:21 UTC, tycebrown commented
> @tycebrown For future reference, please let the reviewer mark the threads as resolved. That way, they can double check that they were handled correctly.

Oh, okay, will keep that in mind.